name: Deploy Application

on:
  push:
    branches:
      - main
      - dev

  workflow_dispatch:

jobs:

  deploy:
    environment: ${{ github.ref_name }}

    uses: Sheshank-27/reusable-workflows/.github/workflows/ecs-ci-cd.yml@main

    with:

      ecr_repository: ${{ vars.ECR_REPOSITORY }}
      ecs_cluster: ${{ vars.ECS_CLUSTER }}
      ecs_service: ${{ vars.ECS_SERVICE }}

      task_definition: python-task

      container_name: python-container

      aws_region: ap-south-1

    secrets:

      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}